esources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: arn:aws:iam::405974261491:role/bhranproject
      FunctionName: my-lambda-function
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 30
      Code:
        S3Bucket: bhranavenewbucket
        S3Key: lambda-code/package.zip